# sitemap settings

template: sitemap.twig
xml_template: assets/sitemap_xml.twig

ignore:
  - /info/home
  - /info/error404
  - /info/bevestiging-nieuwsbrief

ignore_contenttype:
  - fotos
#  - scores
#  - standings